[General]
sessions=1

[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\aq\0\0\x4\t\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\aq\0\0\x4\t)
state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\ar\0\0\x4\n\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[Session0]
D0\color=4279638298
D0\conv_options=0
D0\conversion_type=0
D0\enabled=true
D0\name=D0
D1\color=4287582722
D1\conv_options=0
D1\conversion_type=0
D1\enabled=true
D1\name=D1
D2\color=4291559424
D2\conv_options=0
D2\conversion_type=0
D2\enabled=true
D2\name=D2
D3\color=4294277376
D3\conv_options=0
D3\conversion_type=0
D3\enabled=true
D3\name=D3
D4\color=4293776384
D4\conv_options=0
D4\conversion_type=0
D4\enabled=true
D4\name=D4
D5\color=4285780502
D5\conv_options=0
D5\conversion_type=0
D5\enabled=true
D5\name=D5
D6\color=4281623972
D6\conv_options=0
D6\conversion_type=0
D6\enabled=true
D6\name=D6
D7\color=4285878395
D7\conv_options=0
D7\conversion_type=0
D7\enabled=true
D7\name=D7
decode_signals=0
device\connection_id=usb/1-3
device\model=Logic
device\serial_num=Saleae Logic
device\vendor=Saleae
device_type=hardware
meta_obj0\assoc_view=0
meta_obj0\end_time=22 serialization::archive 20 0 0 0 0 7 96809279 16666668 40910693 28133016 82472229 0 0 0 6
meta_obj0\start_time=22 serialization::archive 20 0 0 0 0 7 96808870 83333331 58861933 4322659 96932983 0 0 0 6
meta_obj0\type=selection
meta_objs=1
view0\D0\trace_height=36
view0\D1\trace_height=36
view0\D2\trace_height=36
view0\D3\trace_height=36
view0\D4\trace_height=36
view0\D5\trace_height=36
view0\D6\trace_height=36
view0\D7\trace_height=36
view0\offset=22 serialization::archive 20 0 0 0 0 7 96808622 76443299 14374681 97463606 888150 0 0 0 6
view0\scale=1.1733963864404696e-08
view0\segment_display_mode=3
view0\splitter_state=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\x46\0\0\a\x1d\x1\0\0\0\x1\x1\0\0\0\x1\0)
view0\v_offset=-228
view0\zero_offset=22 serialization::archive 20 0 0 0 0 0 0 0 0 0 0 0 0 0 6
views=1

[Settings]
Dec_ExportFormat=%s %d: %r: %1
General_Language=en
General_SaveWithSetup=true
General_Style=Fusion
General_Theme=1
Log_BufferSize=500
Log_NotifyOfStacktrace=true
View_ColoredBG=true
View_CursorFillColor=4282137660
View_CursorShowFrequency=true
View_CursorShowInterval=true
View_CursorShowSamples=true
View_DefaultDivHeight=54
View_DefaultLogicHeight=36
View_FillSignalHighAreaColor=398245052
View_FillSignalHighAreas=true
View_ShowHoverMarker=true
View_ShowSamplingPoints=true
View_SnapDistance=15
View_ZoomToFitAfterAcq=true
